import os
import requests
import streamlit as st

st.set_page_config(
    page_title="Corporate Intelligence Chat",
    page_icon="🤖",
    layout="wide"
)

API_URL = os.getenv("API_URL", "http://agent-api:5000/api/research")


# פונקציית עזר לשליחת הודעה ל-Backend
def send_message(user_text: str):
    st.session_state.messages.append({"role": "user", "content": user_text})
    with st.spinner("Analyzing intelligence sources..."):
        try:
            response = requests.post(
                API_URL,
                json={"query": user_text},
                timeout=120
            )
            if response.status_code == 200:
                data = response.json()
                bot_reply = data.get("report", "No response generated by agent.")
                is_safe = data.get("is_safe", True)
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": bot_reply,
                    "is_safe": is_safe
                })
            else:
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": f"Server Error ({response.status_code}): {response.text}",
                    "is_safe": False
                })
        except requests.exceptions.RequestException as e:
            st.session_state.messages.append({
                "role": "assistant",
                "content": f"Failed to connect to backend: {e}",
                "is_safe": False
            })


# אתחול זיכרון השיחה
if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": "Hello! I am your Corporate Intelligence Agent. How can I assist your market analysis today?",
            "is_safe": True
        }
    ]

# סרגל צד עם מאגר השאלות המוכן
with st.sidebar:
    st.markdown("### 🤖 Intelligence Telemetry")
    st.caption("**Engine:** LangGraph ReAct Agent")
    st.caption("**Knowledge:** Qdrant RAG + n8n Webhook")
    st.markdown("---")

    st.markdown("### 🎯 Quick Intelligence Directives")
    st.caption("Click any query to execute immediately:")

    if st.button("🏢 AlphaCorp Vulnerabilities", use_container_width=True):
        send_message("What are the primary weaknesses, vulnerabilities and deployment risks of AlphaCorp?")
        st.rerun()

    if st.button("📈 Tesla Market & News", use_container_width=True):
        send_message("Provide a strategic intelligence report and market sentiment analysis for Tesla.")
        st.rerun()

    if st.button("💻 NVIDIA Competitive Position", use_container_width=True):
        send_message("Evaluate NVIDIA's current market momentum, competitive risks, and recent strategic news.")
        st.rerun()

    if st.button("🛡️ CDC Pet Policy (Guardrail Test)", use_container_width=True):
        send_message("Which dogs are allowed to enter your site?")
        st.rerun()

    st.markdown("---")
    if st.button("🗑️ Clear Conversation", use_container_width=True):
        st.session_state.messages = [
            {
                "role": "assistant",
                "content": "Conversation cleared. Ready for a new directive.",
                "is_safe": True
            }
        ]
        st.rerun()

# כותרת ראשית
st.title("Competitive & Corporate Intelligence Agent")
st.caption("Interactive Chat Interface backed by LangGraph, Qdrant Vector Store, and Live n8n Dispatcher")

# הצגת כל היסטוריית השיחה
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        if not msg.get("is_safe", True):
            st.warning(msg["content"])
        else:
            st.markdown(msg["content"])

# קלט חופשי משורת הצ'אט התחתונה
if prompt := st.chat_input("Type your question or corporate intelligence directive..."):
    send_message(prompt)
    st.rerun()